#
# Dockerfile - docker build script for a standard GlueX sim-recon 
#              container image based on centos 7.
#
# original author: richard.t.jones at uconn.edu
# author: marki at jlab.org
# version: December 23, 2020
#
# usage: [as root] $ docker build Dockerfile .
#

FROM centos:centos7.7.1908

RUN yum install -y gcc-gfortran
